CoinmaniaTask/Models/CoinmaniaDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace CoinmaniaTask.Models
{
    public class CoinmaniaDbContext : DbContext
    {
        public CoinmaniaDbContext(DbContextOptions<CoinmaniaDbContext> options) : base(options)
        {
        }

        public DbSet<Currency> Currencies { get; set; }
        public DbSet<CurrencyHistory> CurrencyHistories { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Currency>().HasKey(c => c.Base);
        }
    }
}

CoinmaniaTask/Models/Currency.cs
using System.ComponentModel.DataAnnotations;

namespace CoinmaniaTask.Models
{
    public class Currency
    {
        [Key]
        public string Base { get; set; }
        public string BaseSymbol { get; set; }
        public string Quote { get; set; }
        public string QuoteSymbol { get; set; }
        public double Price { get; set; }
        public double BuyPrice { get; set; }
        public double SellPrice { get; set; }
        public DateTime LastUpdateDate { get; set; }
    }
}

CoinmaniaTask/Models/CurrencyDataResponse.cs
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace CoinmaniaTask.Models
{
    public class CurrencyDataResponse
    {
        public int StatusCode { get; set; }
        public List<Currency> Data { get; set; }
        public object Message { get; set; }
    }
}

CoinmaniaTask/Models/CurrencyHistory.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace CoinmaniaTask.Models
{
    public class CurrencyHistory
    {
        [Key]
        public int Id { get; set; }

        public string Base { get; set; }
        public string BaseSymbol { get; set; }
        public string Quote { get; set; }
        public string QuoteSymbol { get; set; }
        public double Price { get; set; }
        public double BuyPrice { get; set; }
        public double SellPrice { get; set; }

        public DateTime CreateDate { get; set; }
    }
}

CoinmaniaTask/Controllers/CurrencyController.cs
using CoinmaniaTask.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CoinmaniaTask.Controllers
{
    public class CurrencyController : Controller
    {
        private readonly CoinmaniaDbContext _dbContext;

        public CurrencyController(CoinmaniaDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult GetCurrency(bool sortByPrice, bool sortByBase)
        {
            if (sortByPrice)
            {
                var sortedByPrice = _dbContext.Currencies.OrderBy(x => x.Price).ToList();

                return View(sortedByPrice);
            }

            if (sortByBase)
            {
                var sortedByBase = _dbContext.Currencies.OrderBy(x => x.BaseSymbol).ToList();

                return View(sortedByBase);
            }

            var currencies = _dbContext.Currencies.ToList();
            return View(currencies);
        }

        public IActionResult GetCurrencyHistory(string currency)
        {
            var currencies = _dbContext.CurrencyHistories.Where(x => x.Base == currency && x.CreateDate < DateTime.Now.AddMinutes(-60)).ToList();

            return View(currencies);
        }
    }
}

CoinmaniaTask/Views/Currency/GetCurrency.cshtml
@model IEnumerable<CoinmaniaTask.Models.Currency>

@{
    ViewData["Title"] = "GetCurrency";
}

<h1>Currency</h1>

<a href="@Url.Action("GetCurrency", "Currency", new { sortByBase = true })" class="btn btn-primary">Sort by base</a>
<a href="@Url.Action("GetCurrency", "Currency", new { sortByPrice = true })" class="btn btn-primary">Sort by Price</a>

<table class="table">
    <thead>
        <tr>
            <th>
                Currency
            </th>
            <th>
                Price
            </th>
            <th>
                Last update date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="window.location.href = '@Url.Action("GetCurrencyHistory", "Currency", new { currency = item.BaseSymbol })'">
                <td>
                    @Html.DisplayFor(modelItem => item.BaseSymbol)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastUpdateDate)
                </td>
            </tr>
        }
    </tbody>
</table>

CoinmaniaTask/Views/Currency/GetCurrencyHistory.cshtml
@model IEnumerable<CoinmaniaTask.Models.CurrencyHistory>

@{
    ViewData["Title"] = "GetCurrencyHistory";
}

<h1>GetCurrencyHistory</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Base)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BaseSymbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quote)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.QuoteSymbol)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BuyPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SellPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Base)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BaseSymbol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuoteSymbol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BuyPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SellPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateDate)
            </td>
        </tr>
}
    </tbody>
</table>

CoinmaniaTask/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoinmaniaTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoinmaniaTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoinmaniaTask.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoinmaniaTask</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CoinmaniaTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>